<?php

/**
 * @file
 * Stickynote extends Entity.
 */

 /**
  * Stickynote extends Entity.
  *
  */
 class StickynoteClass extends Entity {

   /**
    * Implements EntityInterface::id().
    */
   public function id() {}

   /**
    * Implements EntityInterface::entityType().
    */
   public function entityType() {}

   /**
    * Implements EntityInterface::bundle().
    */
   public function bundle() {}

   /**
    * Implements EntityInterface::label().
    */
   public function label() {}

   /**
    * Implements EntityInterface::uri().
    */
   public function uri() {}
 }
